### ISSUE TITLE
don't create security groups by default in cloud

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#270]
use a bolean instead to have this enabled.
otherwise we will reach soon the limit of security groups

**Comment by Bischoff** [comment]
Same problem as the images. Maybe removing the prefix is enough. I don't see any problem in sharing a commmon security group for all users.

**Comment by moio** [comment]
@Bischoff we do not have that problem with images, at least in the context of the ECP Cloud, because the prefix is standardized to "susemanager-" there (see example file).

Plan is that we will keep a separate, manually managed main.tf exclusively for image uploading. The same is true for the mirror host.

**Comment by moio** [comment]
Addressed via #275
