### ISSUE TITLE
GPG key has expired in the testsuite repo

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#335]
With a SLE15 RC3 client:
```
[ERROR   ] Command '['zypper', '--non-interactive', '--no-refresh', 'info',
 '-t', 'package', 'libzypp', 'salt', 'salt-minion', 'zypper']' failed with
 return code: 106
[ERROR   ] stdout: Warning: The gpg key signing file 'repomd.xml' has expired.
  Repository:       Repo with new RPMs used for Testsuite (SLE_12_SP1)
  Key Name:         Unsupported <unsupported@suse.de>
  Key Fingerprint:  D88811AF 6B518523 51DF5385 27FA41BD 8A7C64F9
  Key Created:      Mon May  5 11:15:59 2014
  Key Expires:      Fri May  4 11:15:59 2018 (EXPIRED)
  Subkey:           E06C023050C2F156 2008-09-12 [expired: 2018-05-04]
  Rpm Name:         gpg-pubkey-8a7c64f9-536756cf
```

The problem was already there with SLE12 clients, but it was only raising a warning. Now it makes the state fail.

There are two ways to fix it:
 * either update the GPG key in OBS
 * ot add the right option to zypper (`--no-gpg-checks`)

**Comment by mcalmer** [comment]
@Bischoff - either somebody already updated this key or we copy somewhere an old one:

```
$> gpg repomd.xml.key
pub  1024D/8A7C64F9 2008-09-12 [verfällt: 2022-03-14]
uid                            Unsupported <unsupported@suse.de>
sub  2048g/50C2F156 2008-09-12 [verfällt: 2022-03-14]
```

As you can see this key is valid until 2022 . Please verify again.

**Comment by Bischoff** [comment]
Retesting with sle15 rc4...

**Comment by moio** [comment]
@mcalmer repo is created in OBS here:

https://build.suse.de/project/show/Devel:Galaxy:BuildRepo

Key is actually expired:

$ curl http://download.suse.de/ibs/Devel:/Galaxy:/BuildRepo/SLE_12_SP1/repodata/repomd.xml.key | gpg
gpg: WARNING: unsafe permissions on homedir '/home/silvio/.gnupg'
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1699  100  1699    0     0  13701      0 --:--:-- --:--:-- --:--:-- 13701
pub   dsa1024 2008-09-12 [SC] [expired: 2018-05-04]
      D88811AF6B51852351DF538527FA41BD8A7C64F9
uid           Unsupported <unsupported@suse.de>
sub   elg2048 2008-09-12 [E] [expired: 2018-05-04]

This repo has not been refreshed by the BS since a long time:

[TXT] repomd.xml.key 20-Oct-2015 18:18  1.7K   Details

`iosc wipebinaries --all Devel:Galaxy:BuildRepo` did NOT took care of it.

@mcalmer should we just use SLE_12_SP3? Doesn't it make more sense to rename the repo to something generic like "SLE" and switch the OS version from time to time?

**Comment by mcalmer** [comment]
The key is now updated. But we should disable Centos, RedHat and Fedora. We only need one build.

**Comment by moio** [comment]
From the sumaform POV, this is addressed.

Thanks!

**Comment by moio** [comment]
For the record: `iosc wipebinaries --all Devel:Galaxy:BuildRepo` DID work - it just needed a little more time to update the file.

**Comment by Bischoff** [comment]
Thanks guys.
