### ISSUE TITLE
"Released beta" repos

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#422]
We need to investigate why we use `-Beta` repos for `-released`products.

Maybe there was a good reason for that, but we have lost it from sight.

**Comment by moio** [comment]
Sure, the reason is simply that betas are as "released" as final builds are!

In fact we used to call version "stable/nightly/head" - but "stable" is a better name. Betas are "released" but might not be "stable"!

I opened #426 to get rid of them now that 3.2 has been released.

**Comment by MalloZup** [comment]
Yop at that time beta are stable so we forget as manual change.to update the stuff. Normally beaceause after release there is vacation or kickoff so people forget it. The good workflow would be to introduce beta and open an issue for remove them ad todo

**Comment by Bischoff** [comment]
Absolutely. This problem goes far beyond betas only BTW. Following the development cycle is a pain in the neck in general, I remember my suffering when I was adding the testing for 3.2 milestones, and I think both of you have similar experiences.

Thanks silvio for #426 .

**Comment by moio** [comment]
> Following the development cycle is a pain in the neck in general

Well, I am not sure if there is a solution here - sumaform needs to know how to correctly set up product repos, and product repos change more or less at every release. I am not sure if we are ready to standardize on some sort of format long-term at this point.

The only way I currently see is to spread knowledge on how the building and shipping machinery works - especially for QA guys this is fundamental information FMPOV - although yes, sure, that can be painful at times.

I am open to more automated/streamlined solutions if any can be found, of course.

**Comment by MalloZup** [comment]
from my pov here we should just use the benifit of github issues as reminder.
If you are creating `beta`  repo on that phase, you will know that in future this need to be set/changed to release.

For example here:

https://github.com/moio/sumaform/issues/296

I create this issue for the future as reminder, because once the 30 is going ouf of in maintenance phantomjs need to be removed.

I think in general and each software project there are `technical debts` or `removal` or `cleanup`.
My personal method is to keep track of this. 
E.G when i see a pattern in software that is a code smell, i open an issue for remembering or outsourcing that. Because otherwise i will forget next 2 weeks. And this work well for me.

So in my opinion we should open more issues, e.g in sumaform side when there is a reminder etc, but this need to be done during that time :smile: 
Ciao :cupid:
