### ISSUE TITLE
Cloudinit images don't get removed by terraform destroy

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#445]
After `terraform destroy`, `virsh vol-list <pool>` still shows all coudinit volumes.

Is it intended? And if yes, is there a solution to get a cleaned up environment other than writing your own cleanup script?

Ping @MalloZup @juliogonzalez .

**Comment by moio** [comment]
This is not intended and if it happens it can only be a bug on `terraform-provider-libvirt` or (less likely) Terraform itself - or a configuration issue.

Sumaform can't be the culprit here - as it only describes resources and has no notion on actual system state.

I will close this, sorry, can't really help.

**Comment by Bischoff** [comment]
OK, I wil move the issue to terraform-provider-libvirt, thanks for the hint @moio.

**Comment by MalloZup** [comment]
the cloudinit module destroy works as expected. it can be that it is an issue also how you define the resources in the main or an user issue. 
In a similar project `https://github.com/MalloZup/ceph-open-terrarium` i have no issues 
`module.cloudinit.libvirt_cloudinit_disk.cloudinit: Destruction complete ..`
